sudo: required

language: node_js
node_js:
- stable

services:
  - docker

script: npm run build-ui

deploy:
  provider: pages
  local-dir: ui
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

after_deploy: node codegen.js