version: '2'
services:
  bitcoind:
    image: kylemanna/bitcoind
    command: [
      "btc_oneshot",
      "-printtoconsole",
      "-testnet",
      "-rpcallowip=::/0",
      "-rpcuser=test",
      "-rpcpassword=test",
      "-rest",
    ]
  editor:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:80"
    links:
      - bitcoind